apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-app
  namespace: production
  labels:
    app: game-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service-app
  template:
    metadata:
      labels:
        app: game-service-app
    spec:
      containers:
      - name: game-service-app
        image: weflop/game-service-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8084