apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
  namespace: production
  labels:
    app: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      labels:
        app: gateway-service-app
    spec:
      containers:
      - name: gateway-service-app
        image: weflop/gateway-service-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080