apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessions-service-app
  namespace: production
  labels:
    app: sessions-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sessions-service-app
  template:
    metadata:
      labels:
        app: sessions-service-app
    spec:
      containers:
      - name: sessions-service-app
        image: weflop/sessions-service-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8085