apiVersion: v1
kind: Service
metadata:
  name: chat-service-app
  namespace: production
spec:
  selector:
    app: chat-service-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083