apiVersion: v1
kind: Service
metadata:
  name: feedback-service-app
  namespace: production
spec:
  selector:
    app: feedback-service-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082