apiVersion: v1
kind: Service
metadata:
  name: frontend-service-app
  namespace: production
  labels:           
    app: frontend-service-app
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: frontend-service-app