apiVersion: v1
kind: Service
metadata:
  name: gateway-service-app
  namespace: production
spec:
  selector:
    app: gateway-service-app
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086