apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: production
  labels:           
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:          # Map any Pod with the specified labels to this service
    app: redis
    role: master