apiVersion: v1
kind: Service
metadata:
  name: sessions-service-app
  namespace: production
  labels:           
    app: sessions-service-app
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:          # Map any Pod with the specified labels to this service
    app: sessions-service-app